---
title: Búho Social
timezone: UTC
collections:
  clients:
    title: Clients
    output: true
  posts:
    title: Posts
    output: true
  services:
    title: Services
    output: true
  team:
    title: Team
    output: false
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: clients
  values:
    image:
    is-home-featured:
    is-artist-and-label-press-featured:
    is-events-press-featured:
    is-daytime-radio-featured:
    is-specialist-radio-and-club-featured:
    is-streaming-promotion-featured:
    is-client-featured:
    website:
    facebook:
    twitter:
    instagram:
    spotify:
    soundcloud:
    youtube:
    apple:
- scope:
    path: ''
    type: services
  values:
    service:
    subtitle:
    excerpt:
- scope:
    path: ''
    type: team
  values:
    image:
    job-title:
    is-featured:
    email:
url: https://www.buhosocial.mx
description: Somos una agencia de comunicación de Guadalajara especializada en comunicación y generacion de contenido en redes sociales.
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
- jekyll/imgix
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: Búho Social. Todos los derechos reservados.
email: buhosocial00@gmail.com
google_site_verification: CeWh3WoLFVL6BBnk6I3hfi5WBCKQnw5fpXA4l8nu0pU
analytics:
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: https://www.facebook.com/buhosocial/
  instagram: https://www.instagram.com/buhosocial
  twitter: https://twitter.com/buhosocial
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
